### ISSUE TITLE
Documentation / Example JS Bin for Downloading MIDI with CDN not working with latest version

### ISSUE THREAD

**Issue by seeingthru** [scribbletune/scribbletune#100]
The example JS Bin on the bottom of this page: https://scribbletune.com/documentation/core/midi

doesn't seem to work with the latest version of Scribbletune.

Is it still possible to download midi files using just the CDN?

Thanks!

**Comment by misterflippy** [comment]
I poked around in https://cdnjs.cloudflare.com/ajax/libs/scribbletune/3.5.3/scribbletune.js a little bit, and it looks like the midi function no longer uses the callback structure and just returns the byte stream from the function. Whether this is intentional or not, the following seems to work for me:

```javascript
var bytes = scribble.midi([].concat(clip), null);
downloadMidi(bytes);

function downloadMidi(bytes){
//code to create link to download
}
```

**Comment by walmik** [comment]
Thank you @seeingthru and @misterflippy (and apologies for the delay in responding here!)

I ve updated the documentation and also added a sample HTML to solve this issue. Please refer to this snippet -> https://github.com/scribbletune/scribbletune/blob/master/dist/download.html#L13-L41

Unfortunately JS Bin wont let me create a demo of a downloadable link as the bins are iframed. Hence created a HTML page instead. 

I m planning to add this as a feature within Scribbletune itself. This will make the existing `midi` method work as is and in the browser context will return the link that users can simply inject in their page. I ll update here right after.

**Comment by walmik** [comment]
Done. V3.6.1 is now published with download MIDI file method baked into Scribbletune :)
