### ISSUE TITLE
Support for Tone 14

### ISSUE THREAD

**Issue by qchenevier** [scribbletune/scribbletune#105]
Hello,

The next version of Tone (v14) breaks scribbletune. It is coming soon (see https://github.com/Tonejs/Tone.js/issues/680) with a lot of improvements (see the [documentation](https://tonejs.github.io/docs/14.7.7/)).

I guess it's because `Master` has been renamed in `Destination` between v13 and v14 and so it breaks when use `Tone.Master` in [browserClip.ts](https://github.com/scribbletune/scribbletune/blob/master/src/browserClip.ts): example:
```javascript
  if (params.instrument) {
    if (params.volume) {
      params.instrument.volume.value = params.volume;
    }
    params.instrument.chain(...effects, Tone.Master); // we should use Tone.Destination instead

// ....
```

If you wish to use it now: you can use the Tone v14 from the [cdn](https://cdnjs.cloudflare.com/ajax/libs/tone/14.7.7/Tone.js) by monkeypatching the module before using scribbletune:

```javascript
import * as scribble from "scribbletune";
Tone.Master = Tone.Destination; // ugly monkey patch but it works
```

@walmik thoughts on how to support this ?

**Comment by walmik** [comment]
Thank you @qchenevier ! I ve bumped minor version and published v3.8.0 after merging your PR for this issue. Later we can move to Tone.Destination for good as part of v4 (whenever that happens)
