### ISSUE TITLE
Error on the https://scribbletune.com/documentation/max webpage

### ISSUE THREAD

**Issue by JanZaion** [scribbletune/scribbletune#143]
Hello Walmik,

I believe that there is an error in your tutorial on how to get Scribbletune working in Max. You provide the following code snippet:

```
/*global post:true*/
const scribble = require('scribbletune');

module.exports = function(scale) {
post(scale);
}
```

This simply takes any argument and prints it to the Max console.

I believe the correct code is the following:

```
/*global post:true*/
const scribble = require('scribbletune');

module.exports = function(scale) {
  post(scribble.scale(scale));
};
```

Or at least this is the way that worked for me.

Cheers! :)

**Comment by walmik** [comment]
Hello @JanZaion thank you for your comment here. I ll fix the docs!

**Comment by walmik** [comment]
I ve updated the docs @JanZaion (apologies for the delay!)
Please close this issue if all good 👍 https://scribbletune.com/documentation/max

**Comment by JanZaion** [comment]
Yep, all good :)
