### ISSUE TITLE
Triplets problem?

### ISSUE THREAD

**Issue by vsntn** [scribbletune/scribbletune#148]
Hi, I noticed scribbletune has a problem when you use Triplets like this [xxx], the problem is that the midi gets out of the grid like this, even if you use triplets only: 

<img width="698" alt="TRIPLETS" src="https://user-images.githubusercontent.com/82344685/114323803-56e23200-9afd-11eb-8599-335d3816103c.png">

There is a solution to this problem? :)

**Comment by walmik** [comment]
Hi @vsntn I can confirm this issue. Thanks for noting it down!

**Comment by vsntn** [comment]
> Hi @vsntn I can confirm this issue. Thanks for noting it down!

Hi I'm new to Scribbletune, is this a recent bug or has this always had that problem? Would it be something very difficult to solve or is it possible that it will be solved in a short time?

**Comment by walmik** [comment]
I d say this has always been there. To fix it some amount of rounding off based on the current subdiv value might be needed [here](https://github.com/scribbletune/scribbletune/blob/master/src/clip.ts#L174) to snuggly fit the notes for triplets.

**Comment by vsntn** [comment]
> I d say this has always been there. To fix it some amount of rounding off based on the current subdiv value might be needed [here](https://github.com/scribbletune/scribbletune/blob/master/src/clip.ts#L174) to snuggly fit the notes for triplets.

It would be great if that bug could be solved, good luck! :)

**Comment by walmik** [comment]
HI @vsntn this issue is now fixed in v4.1.0 
Would be great if you could verify!

**Comment by vsntn** [comment]
> HI @vsntn this issue is now fixed in v4.1.0
> Would be great if you could verify!

Yes! It's fixed :)
