### ISSUE TITLE
`types` should point to `./dist/index.d.ts` now

### ISSUE THREAD

**Issue by brandongregoryscott** [scribbletune/scribbletune#173]
Hey there! I am using scribbletune (v5.0.1) in another project and I see the type definitions included in the package bundle, but TypeScript is saying it can't find the definitions: 

```
Cannot find module 'scribbletune' or its corresponding type declarations.ts(2307)
```

![image](https://user-images.githubusercontent.com/11774799/192660661-74cca007-e6f7-4ca7-b575-20154ddbe139.png)

If I edit the `package.json` to point the `types` field to `./dist/index.d.ts` and restart my TS server, it seems to pick them up correctly.

**Comment by walmik** [comment]
Thank you @brandongregoryscott ! I ll fix this tonight once I get home. It looks like a side effect of adding dist to the exports list in the package.

**Comment by walmik** [comment]
@brandongregoryscott 
Just published v5.0.2 with the fix. You certainly dont have to but would be nice if you could verify once.

**Comment by brandongregoryscott** [comment]
Looks like it's working now - thanks for the quick fix @walmik!

**Comment by walmik** [comment]
thank you @brandongregoryscott !
