### ISSUE TITLE
Can't find the correct chrods/pattern

### ISSUE THREAD

**Issue by jersobh** [scribbletune/scribbletune#74]
I'm trying to write this song, but it's far from being similar to this

   Am
Una mattina mi sono alzato,

O bella ciao, bella ciao,

Bella ciao, ciao, ciao,
      Dm               Am
Una mattina mi sono alzato,
        E          Am   (E,Am)
E ho trovato l'invasor.

**Comment by walmik** [comment]
Is there some issue in Scribbletune? Please let me know the details of the issue you face. If its just chords or patterns you re looking for a particular song then I believe you ll have to figure those out by yourself.

**Comment by walmik** [comment]
Closing this issue as it doesnt seem to be related to Scribbletune per say.
