### ISSUE TITLE
Fix coverage

### ISSUE THREAD

**Issue by walmik** [scribbletune/scribbletune#76]
Recent move from gulp to npm and using nyc has caused coverage reports to not work any more(they are always empty)
![nyc](https://user-images.githubusercontent.com/467030/46585341-98715e00-ca24-11e8-9857-56f553b3b676.png)

@DeekshithShetty It would be nice if you take a look as well.

**Comment by DeekshithShetty** [comment]
@walmik Will take a look.

**Comment by nthngalone** [comment]
I have submitted a PR that should resolve this.

- Reenabled instrumentation in the nyc config file
- Added babel-register as a required module for nyc to preload.  Based on some blog posts, this seems to be the recommended approach to working with newer ES2015+ modules.  I'm thinking the instrumentation didn't know how to work with these modules and failed to give any statistics at all.

My runs locally are now showing coverage statistics.
```
----------------|----------|----------|----------|----------|-------------------|
File            |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------------|----------|----------|----------|----------|-------------------|
All files       |     62.9 |    47.39 |    51.79 |    62.75 |                   |
 arp.js         |    92.86 |    81.82 |      100 |    92.59 |             41,45 |
 browserClip.js |        0 |        0 |        0 |        0 |... 37,140,141,144 |
 chord.js       |    96.43 |    94.44 |      100 |    96.43 |                42 |
 clip.js        |    97.92 |     90.7 |      100 |    97.87 |                90 |
 index.js       |      100 |       50 |      100 |      100 |                18 |
 midi.js        |    93.55 |    83.33 |      100 |    93.55 |             57,58 |
 progression.js |    85.71 |    78.57 |       75 |    85.71 |    14,25,26,28,58 |
 scale.js       |    84.62 |    66.67 |       50 |    84.62 |             17,23 |
 session.js     |        0 |        0 |        0 |        0 |... 15,116,124,125 |
 utils.js       |      100 |      100 |      100 |      100 |                   |
----------------|----------|----------|----------|----------|-------------------|
```

**Comment by walmik** [comment]
@nthngalone Thank you very much for adding the fix for this! I ve just merged it in.
@DeekshithShetty looks like we are "covered" for this one. Thanks to you too for your original effort to bring in coverage in the first place :)

**Comment by nthngalone** [comment]
No problem!
