### ISSUE TITLE
Create a contributing.md

### ISSUE THREAD

**Issue by walmik** [scribbletune/scribbletune#78]
At the very least it should have some basic guidelines such as add tests for new code changes. It should also make a mention that Scribbletune works in the browser via Tone.js as well as in the terminal, hence a new code change needs to be such that it ll work in both the places. If it cannot, then that should be mentioned with some reasoning so that we can plan for it's creation in a subsequent code change.

**Comment by gabrielbarker** [comment]
Hey, saw this issue and thought I'd take a shot at it. Let me know if there's anything you want me to take out or put in!
