### ISSUE TITLE
scale.js has .toLowerCase hardcoded, but Tone has two scales with uppercase letters

### ISSUE THREAD

**Issue by bluelotusmedia** [scribbletune/scribbletune#82]
I get errors whenever calling "lydian #5P pentatonic" or "minor #7M pentatonic" due to the hardcoded toLowerCase in scale.js. Every other scale seems to be lowercase, and I have no problems calling them. I think this is a bug. Thanks.

P.S. Love scribbletune!

**Comment by walmik** [comment]
@bluelotusmedia Thank you for sharing this observation - and thank you for the PS as well :)
I ll look into this once I get some time. Maybe the solve would be to allow both ways of setting up a scale so that we dont have to remember what casing works.

**Comment by walmik** [comment]
@bluelotusmedia this issue is now fixed in version 2.0.1, if you get some time could you please verify?
