### ISSUE TITLE
[QUESTION] Where I can find the CI service?

### ISSUE THREAD

**Issue by gustavosizilio** [scribbletune/scribbletune#83]
Is this project using continuous integration services (e.g., Travis-CI or Jenkings)? Or has it used at any point of its lifetime?

**Comment by walmik** [comment]
Scribbletune uses Travis, here s the config for it https://github.com/scribbletune/scribbletune/blob/master/.travis.yml

**Comment by gustavosizilio** [comment]
Ah! I see the problem. I was trying to get builds on https://api.travis-ci.org but you got a private repo which uses https://api.travis-ci.org. Thank you very much! and sorry for taking your time :)
