### ISSUE TITLE
noteLength no longer seems to have an impact on the generated note length

### ISSUE THREAD

**Issue by bendorge** [scribbletune/scribbletune#84]
I had used an older version of Scribbletune and then decided to upgrade. 

Without changing my code, nodeLength no longer appears to have an impact. What used to generate eight bars, now generates 32:

Example: 

clips[patternName] = scribble.clip({
	notes: soundBank[patternName].notes,
	pattern: soundBank[patternName].pattern,
	sizzle: sizzleSetting,
	noteLength: noteLengthSetting
});

If noteLengthSetting was set to 1/16, 'x---x---x---x---'.repeat(8) used to result in 8 bars of kicks (4 per bar). Now, changing noteLengthSetting has zero impact. I manually added 'xxxx'.repeat(8) and that worked as we would expect in the upgraded version. 

Without changing the pattern syntax, how can I change the note length?

**Comment by walmik** [comment]
Hi @bendorge ! Sorry for this lack of communication from my side for the updated version. The noteLength property was removed in favor of the tidal syntax that Tone.js uses (Scribbletune also uses it now to be able to support using it on the browser) Which means, by default `x` is a quarter note. To get around this such that it can use the pattern you already have, you can set a new (unfortunately undocumented) property called `subdiv`:

```
const scribble = require('scribbletune');
const clip = scribble.clip({
  notes: 'C3',
  pattern: 'x---x---x---x---',
  subdiv: '16n' // the default is '4n' (quarter note)
});
scribble.midi(clip);
```

`subdiv` lets you set the default length of what `x` is. Another thing that we get from tidal patterns is the square braces to subdivide a note dynamically.

So if default is a quarter note `4n`, then we can subdivide with square braces:

```
xxx[xx]
```

In this pattern the first 3 x will play the note at quarter note, but will subdivide the last note to 2 quarter notes.

```
[xxx]
```

Here the quarter note is divided into 3 leading to a triplet.

Something like `'[xxx]'.repeat(4)` will create a nice 4x4 triplet pattern :)

**Comment by bendorge** [comment]
subdiv solves the issue. Thanks so much for all your great work Walmik!
