### ISSUE TITLE
TypeError from "Download Midi from Browser" code example

### ISSUE THREAD

**Issue by gntsketches** [scribbletune/scribbletune#86]
Hi, when I try the code you have provided in this section, I get: "TypeError: fs.writeFile is not a function" (in /nodemodules/scribbletune/src/midi.js:45):

```
  42 |     return;
  43 |   }
  44 | 
> 45 |   fs.writeFile(fileName, bytes, 'binary', callback);
  46 | };
  47 | 
  48 | function createFileFromNotes(notes) {
```

For context, I am running your code in a React app. (Set up with create-react-app.) I'm not sure if that  would affect anything. The JSBin link does download the file.

Thanks for creating this awesome library, btw! Also this is the first I have seen/heard of the ability to write Midi in-browser - feeling hopeful! :)

**Comment by walmik** [comment]
Hi @gntsketches ! Thank you so much for the kind comments... I too had a similar feeling (hopeful) when I learnt how to generate MIDI files in the browser. If it interests you, I had put together an example for using Scribbletune's `arp` feature: https://scribbletune.github.io/live/rpg8.html

For the issue you pointed out, have you followed the steps here for making this work in the browser? https://scribbletune.com/documentation/installation

I ve also put together a very simple example on JS Bin in case you wanna take a look (Please note, it might instantly download a MIDI file if your JS Bin is set to auto run JS) https://jsbin.com/nabirinovo/edit?html,js,console,output

Lemme know if this works out for you, if not I ll help more :)

**Comment by gntsketches** [comment]
Thanks for your response & help! Feeling foolish, I did miss all that, had just npm installed it. 

When I ran npx webpack script.js -o main.js, I got these errors and warnings.

"Insufficient number of arguments or no entry found.
Alternatively, run 'webpack(-cli) --help' for usage info.

Hash: ef8170712215f39d2ef0
Version: webpack 4.30.0
Time: 132ms
Built at: 04/24/2019 2:21:02 PM

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/concepts/mode/

ERROR in Entry module not found: Error: Can't resolve 'script.js' in (...) "

**Comment by gntsketches** [comment]
Hi again, wondering if you've got any further through on the error I noted above?

**Comment by walmik** [comment]
Hii @gntsketches Thank you for persisting on this issue. 

I figured we dont have a webpack config hence there s no way to provide the override for `fs`. I ve now added a bare minimum webpack config file to the setup which should take care of this issue as well as set mode to  "none" so that it wont try to optimize.

Can you please try the updated installation instructions on https://scribbletune.com/documentation/installation

The 2 changes are:
- addition of a webpack.config.js to the setup
- run `npx webpack` instead of `npx webpack script.js -o main.js`

Lemme know how it goes!

**Comment by gntsketches** [comment]
Hi, thank you for this! In the context of create-react-app I was not able to make this work, so decided to start fresh. The procedure seems to be working until I run `python -m SimpleHTTPServer 3000` at the command line, then I'm getting this error: "C:\Users\Gregory Tippett\AppData\Local\Programs\Python\Python37-32\python.exe: No module named SimpleHTTPServer" 

I'm a relatively new dev and unfamiliar with both Python & Webpack, (as I indicated above, I'm using the out-of-the-box quickstart setup for React) and it seems likely enough that this is a simple error on my part - I don't expect you to walk me through these things that I should learn on my own! 

Anyway the cdn does seem to be working, which is fine for getting started. Thank you for building this, and would love to correspond with you more as I get my project together :)

**Comment by walmik** [comment]
Hi @gntsketches 

Yes you do need to learn on your own, but honestly the tooling around today's frontend apps can get a bit difficult at times and it s okay to seek help. In fact create-react-app was born out of this very fact that folks were getting lost in the tooling and it took days to get close to anywhere near writing their app! 

Hence, if you are already using create-react-app, then no need of any of the things I showed in my documentation! You should be able to use scribbletune directly. I ve used create-react-app in the past for a project that i m **not** currently working on actively but you can take a look at it if you like: https://github.com/scribbletune/live Please take a look inside the src/modules/Live folder to see how I m using scribbletune with React and Redux to produce a browser based application based on a rudimentary idea of Ableton Live's Session view if you are familiar with that. 

Lemme know if you get stuck somewhere, I ll try to help as time permits. I ll try to put together some documentation for using create-react-app whenever I get some free time (might not happen right away). Honestly, the documentation site is open sourced as well in case you wanna take a stab a it. After all the best way to learn something is to teach it :)

**Comment by walmik** [comment]
For the python error (since you almost got till that point) looks like you have python 3, my instructions assumed python 2.7 :P Can you try this command instead `python -m http.server 3000` SimpleHTTPServer has been replaced by http.server in python 3.

**Comment by walmik** [comment]
Hope it s good to close this issue now @gntsketches :)
