### ISSUE TITLE
documentation needs an update

### ISSUE THREAD

**Issue by JasonDeving** [scribbletune/scribbletune#88]
https://scribbletune.com/

documentation needs update. Some of the example scripts don't work. I had to look into the build to fix the script. Thanks.

scribble.getChordsByProgression() // works

https://scribbletune.com/examples/melody
```js
const chords = scribble.progression.getChords('C4 minor', 'ii III ii v'); //i III ii v // line 2 doesn't work
```

**Comment by walmik** [comment]
Hi @JasonDeving thank you for pointing that out. I ve fixed the gist. Can you please check if it looks fine?

**Comment by JasonDeving** [comment]
it's fixed
