### ISSUE TITLE
Set BPM

### ISSUE THREAD

**Issue by walmik** [scribbletune/scribbletune#9]

**Comment by walmik** [comment]
BPM can be set for the browser version via Tone's transport method exposed in Scribbletune 1.0.0 alpha.1 onward. For instance, in the browser, you can do 
```
const scribble = require('scribbletune');
scribble.transport.start(140); // BPM is set to 140
```

However this is still a pending item for the MIDI generation part from the terminal.

**Comment by aauffray** [comment]
Any news on this one ?

**Comment by walmik** [comment]
Thanks to @Kylir s #112 PR I m closing this almost 5 year old issue!
