### ISSUE TITLE
What range of numbers does `clip.volume` accept? (jsdoc? documentation)

### ISSUE THREAD

**Issue by nfreear** [scribbletune/scribbletune#90]
Hi @walmik,

I'm loving _Scribbletune_ -- thank you! 

I've being trying to set a lower volume for a clip (for example a `kick.wav`-based one), relative to other clips. What are valid volume numbers please? (I tried 5, 1, 0.5, `-10` as in decibels ...!)

And, would you accept a pull request, for `jsdoc` comments added to the [`ClipParams` interface](https://github.com/scribbletune/scribbletune/blob/master/src/typings.d.ts#L20-L42)? Perhaps in a separate `.ts` file, imported into `typings.d.ts` (not sure if/how that works)?

I know you've started [documenting some properties of `clip` here](https://github.com/scribbletune/scribbletune.com/blob/master/_pages/clip.md) -- I wonder if it would be appropriate to document nearer the code?

Thanks,

Nick

---
* Follows on from #25 -- _Add JSDoc ..._

**Comment by walmik** [comment]
Hi @nfreear thank you for your kind comments! I think the volume is in decibels and ranges from -60 to 12. Here is a example of using Scribbletune to create a very basic Ableton Live like experience: https://github.com/scribbletune/live/blob/live/src/tracks/final.js#L78

PRs are welcome!

**Comment by nfreear** [comment]
OK, I've added as much detail as I can for each property in the `ClipParams` interface ... Are you able to add any corrections or details where I've indicated "_??_" please?

Note, I'm looking at [TypeDoc](https://typedoc.org/), in place of JSDoc. (_It just works!_)

## ClipParams ##

  * `notes: string | (string | string[])[]` -- A string or array of notes. Default: `[ 'C4' ]`.
     - Example: `'C4 D4 C4 D#4 C4 D4 C4 Bb3'`
  * `pattern: string` -- Music pattern/ rhythm, expressed using `x_-R[]`. Default: `'x'`. Example: `x_x_`.
  * `shuffle?: boolean` -- Randomize the order of the notes set in the clip. Default: `false`.
  * `arpegiate?: boolean` -- Default: `false`.
  * `subdiv?: string` -- Sub-division - what each `x` is worth in a `pattern` ?? Default: `'4n'`. Example: `'1m '`.
      - See: https://github.com/Tonejs/Tone.js/wiki/Time#notation
  * `amp?: number` -- Amplitude? Of what? 'sample'? Range? Default: `100`. Example: `127`.
  * `sizzle?: boolean | SizzleStyle` -- Add a “sizzle” (in a manner of speaking) to the levels (volume). Default: `false`.
  * `accent?: string` -- Accentuate the specified notes in the clip, expressed using `x-` (on/off). Example: `'x--x'`;
  * `accentLow?: number` -- Default: `70`.
  * `sizzleReps?: number` -- Number of sizzle repetitions. Default: `1`;
  * `randomNotes?: null | string | (string | string[])[]` -- ?? Default: `null`;
  * `synth?: any` -- The name of a synth, listed in `Tone.js`. For example, `'PolySynth'`.
      - See: https://github.com/Tonejs/Tone.js/tree/dev/Tone/instrument
  * `instrument?: any` -- A `Tone` instance ?? Example: `instrument: getToneMonoSynth('MonoSynth:BassGuitar')`
      - See :~ https://github.com/scribbletune/sampler#tone-monosynths
  * `sample?: any` -- URL/ path to an instrument sample in an audio file. Supports WAV, MP3 and OGG formats ??
      - For example, `'https://scribbletune.com/sounds/kick.wav'`;
  * `buffer?: any` -- A `Tone.Buffer` instance ??
      - See: https://tonejs.github.io/docs/13.8.25/Buffer
  * `samples?: any` -- A dictionary of audio samples expressed as a `{ 'note' : 'URI', ... }` object.
      - Example: `{ 'C3': 'https://.../piano48.wav', 'C#3': 'https://.../piano49.wav', ... }`
  * `sampler?: any` -- A `Promise` that resolves to a `Tone.Sampler`. Example: `sampler: getSampler('korgBass')`
      - See: https://github.com/scribbletune/sampler#sampler
      - (Uses: A `Tone.Sampler` instance "_Automatically interpolates between a set of pitched samples._")
      - (Uses: https://tonejs.github.io/docs/13.8.25/Sampler)
  * `player?: any` -- A `Tone.Player` instance. "_Tone.Player is an audio file player with start, loop, and stop functions._" ??
      - See: https://tonejs.github.io/docs/13.8.25/Player
  * `dur?: string` -- Duration -- duration of the `clip` ?? Example: `'32n'`, `'1m'`
      - See: https://github.com/Tonejs/Tone.js/wiki/Time
  * `effects?: string[]` -- Name of an effect listed at https://github.com/Tonejs/Tone.js/tree/dev/Tone/effect
      - Example: `[ 'Chorus' ]`
  * `volume?: number` -- Volume in decibels, in the range `-60` to `+12`. Default: `0` (?) For example: `-18`.
      - (Note, not applicable to `sample` - it gives an error.)
      - See: https://tonejs.github.io/docs/13.8.25/Volume

---

Yours, Nick

**Comment by walmik** [comment]
Firstly this is great stuff Nick, thank you for taking the time to do this so systematically.

I ll address some of your questions inline

```
subdiv?: string -- Sub-division - what each x is worth in a pattern ?? Default: '4n'. Example: '1m '.
See: https://github.com/Tonejs/Tone.js/wiki/Time#notation
```
Each x is a quarter note by default. However x, -, _, [, ] and R are not related to Tone.js They are Scribbletune's pattern language which can be adapted to output MIDI files or Tone.js sequences.

```
amp?: number -- Amplitude? Of what? 'sample'? Range? Default: 100. Example: 127.
```
`amp` is the default MIDI level/volume of a note. It s also used as upper bound for deciding the range for things like accents and sizzles (where the lower bound is `accentLow`). I can see that the name is misleading and maybe we should rename it appropriately at some point. 

```
instrument?: any -- A Tone instance ?? Example: instrument: getToneMonoSynth('MonoSynth:BassGuitar')
See :~ https://github.com/scribbletune/sampler#tone-monosynths
```
Yes this is a Tone.js instrument and used only in the browser version of Scribbletune.

```
sample?: any -- URL/ path to an instrument sample in an audio file. Supports WAV, MP3 and OGG formats ??
For example, 'https://scribbletune.com/sounds/kick.wav';
```
I have tried `wav` and it works fine. But I think `mp3` hadnt worked. `ogg` I havent tried yet.

```
buffer?: any -- A Tone.Buffer instance ??
See: https://tonejs.github.io/docs/13.8.25/Buffer
```
I think this buffer can be a Tone buffer or any audio buffer really

```
dur?: string -- Duration -- duration of the clip ?? Example: '32n', '1m'
See: https://github.com/Tonejs/Tone.js/wiki/Time
```
`dur` is the duration of the individual sample that maybe used in a browser clip. So if you had a sample called kick.wav, it will play out till it's end. But Tone lets you set how long it shud be played for each noteOn event. `dur` lets you define that duration. There s a bunch of work pending with this param and there s a open PR #77 for reference on what that pending work is.. i am hoping the original author of that PR would be able to find some time some day :)

I hope I ve not missed something. Please let me know if I have. Also it would be nice to have some representation of all this in the [documentation website's repo](https://github.com/scribbletune/scribbletune.com) for this. Would be really nice if you can create a PR there too :) 

Many thanks for your inputs and time!

**Comment by walmik** [comment]
Hope it s ok to close this now @nfreear thank you again for your contributions!

**Comment by nfreear** [comment]
Hi @walmik ... yes of course. Stay safe! N.
