### ISSUE TITLE
Alternative CDN -- beware version differences!

### ISSUE THREAD

**Issue by nfreear** [scribbletune/scribbletune#92]
Hi,

Just to note that as well as _CDNJS_:

```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/tone/13.8.28/Tone.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/scribbletune/3.3.2/scribbletune.js"></script>
```

... There is [UNPKG](https://unpkg.com/) ~~ based on `npm publish`:

```html
<script src="https://unpkg.com/tone@13.8.25/build/Tone.js"></script>
<script src="https://unpkg.com/scribbletune@3.4.1/dist/scribbletune.js"></script>
```

Has the maintainer of `Tone.js` missed some `npm publish`s?

Ta,

Nick

**Comment by walmik** [comment]
Closing as it seems to be related with Tone.js
Having said that ^ Scribbletune seems to be working fine with Tone. [Sample app](https://stackblitz.com/edit/scale-player).
