### ISSUE TITLE
session.createChannel() does not return new channel

### ISSUE THREAD

**Issue by threex0** [scribbletune/scribbletune#95]
The documentation here https://scribbletune.com/documentation/browser/channel describes that session.createChannel is supposed to return the newly created channel to be used with the methods of startClip() for instance.

However the code here:  https://github.com/scribbletune/scribbletune/blob/bf408519fa8677b0f5696ae6554d6b0c8d4d044d/src/session.ts in session.ts shows this method doesn't return anything, only creating the channel via the constructor returns the channel.

I've called the channels directly using session.sessionChannels[0].startClip(0), however it seems like the documentation and the code don't line up, even when using the versions specifically included in the documentation.

Just though I should point this out since it had me stuck for a minute when working with this library

**Comment by walmik** [comment]
Hi @threex0 Thank you so much for pointing this out! I ve [fixed this issue in patch version 3.4.6 ](https://github.com/scribbletune/scribbletune/commit/729ca10febb7c765997cfe3067b3679edfee0a57#diff-f3fe9c4fe673e665c8df5914c3b9c9a0) and published it. If you are pulling the browser version from CDNjs then it might take few days for it sync up with the update. In the mean time you could you please use dist/scribbletune.js to check if you re getting the channel as it suggests in the docs?
