### ISSUE TITLE
dynamic clips

### ISSUE THREAD

**Issue by healzer** [scribbletune/scribbletune#98]
Hi guys,

I have a problem that I'm trying to solve, I'm using ToneJS with Scribbletune.

I want to dynamically change the pattern of certain clips. Currently I am doing this by stopping and disposing all clips, then re-creating the clips with a different pattern. But the problem is it's also clearing the internal buffer, making me wait for the ToneBuffer's "load" event before playing the new clips.

Is there an alternative solution to this? Is there a way to change the pattern of a clip without having to re-create the clip?

**Comment by healzer** [comment]
I solved this issue by using a buffer:
const buffer1 = new Tone.Buffer('./samples/custom/kick.wav')
function doSomething() {
        scribble.clip({
            sample: buffer1,
            pattern: 'x'
        }).play()
}

**Comment by walmik** [comment]
this is excellent @healzer ! Thanks for suggesting this.. I ll update it in the docs over the weekend.

**Comment by healzer** [comment]
>  btw, clip also accepts buffer as a param too 

Well yeah, that's what I used in my code sample :)
Either way, many thanks for making this addon, it allows less musical people like me to still make something
